# Test build your arduino libraries with travis and the official arduino tool chain
 
# assumes directory structure
# /NullStream
#   NullStream.h
#   NullStream.cpp
#   examples
#     NullStreamExample
#       NullStreamExample.ino
 
language: cpp

compiler:
 - gcc
 
install:
 # arduino
 - wget http://downloads-02.arduino.cc/arduino-1.6.1-linux64.tar.xz
 - ls -alF
 - tar Jxf arduino-1.6.1-linux64.tar.xz
 - sudo mv arduino-1.6.1 /usr/local/share/arduino
 - git clone -b master https://github.com/scottdarch/Arturo.git
 - cd Arturo && sudo make install && cd ../

before_script:
  # put your source files in a folder under a new libraries folder
 - sudo mkdir /usr/src/arduino
 - sudo mkdir /usr/src/arduino/libraries
 - sudo ln -s $TRAVIS_BUILD_DIR /usr/src/arduino/libraries/DualVNH5019MotorShieldMod3
 
script:
 - cd /usr/src/arduino/libraries/DualVNH5019MotorShieldMod3/examples/Demo/Demo.ino && ano build --board-model mega
