# Test build your arduino libraries with travis and Arturo
 
language:
 - cpp

compiler:
 - gcc
 
install:
 #- sudo apt-get update
 #- sudo apt-get upgrade
 #- sudo apt-get dist-upgrade
 #- sudo apt-get install arduino=1.6.1 arduino-core=1.6.1
 # Install arduino 1.6.1
 - wget http://downloads-02.arduino.cc/arduino-1.6.1-linux64.tar.xz
 - tar Jxf arduino-1.6.1-linux64.tar.xz
 - ls -alF
 - sudo mv arduino-1.6.1 /usr/local/share/arduino
 # put your source files in a folder under a new libraries folder
 - sudo mkdir /usr/src/arduino
 - sudo mkdir /usr/src/arduino/libraries
 - sudo mkdir /usr/local/share/arduino/libraries
 - sudo ln -s $TRAVIS_BUILD_DIR /usr/src/arduino/libraries/DualVNH5019MotorShieldMod3
 - sudo ln -s $TRAVIS_BUILD_DIR /usr/local/share/arduino/libraries/DualVNH5019MotorShieldMod3
 - ls -alF
 # Try copying libraries to lib directory 
 #- sudo mkdir /DualVNH5019MotorShieldMod3/lib
 #- sudo ln -s $TRAVIS_BUILD_DIR /DualVNH5019MotorShieldMod3/lib/DualVNH5019MotorShieldMod3
 # install arturo
 - git clone -b master https://github.com/scottdarch/Arturo.git
 - cd Arturo && sudo make install && cd ../

before_script:
 #- sudo setenv DISPLAY :0.0
 #- arduino --install-library
 - ls -alF

script:
 - ano clean
 - cd DualVNH5019MotorShieldMod3 && ano build --board-model mega --source-dir . --cpu atmega2560
 - ls -alF
