# Test build your arduino libraries with travis and Arturo
language: python

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  directories:
    - "~/.platformio"

matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env:
        - PLATFORMIO_CI_EXTRA_ARGS="--board=megaatmega2560" PLATFORMIO_CI_SRC=DualVNH5019MotorShieldMod3/examples/Demo/Demo.ino
    - python: "2.7"
      env:
        - PLATFORMIO_CI_EXTRA_ARGS="--board=due" PLATFORMIO_CI_SRC=DualVNH5019MotorShieldMod3/examples/Demo/Demo.ino
    - python: "2.7"
      env:
        - PLATFORMIO_CI_EXTRA_ARGS="--board=uno" PLATFORMIO_CI_SRC=DualVNH5019MotorShieldMod3/examples/Demo/Demo.ino
    - python: "2.7"
      env:
        - PLATFORMIO_CI_EXTRA_ARGS="--board=megaatmega2560" PLATFORMIO_CI_SRC=DualVNH5019MotorShieldMod3/examples/Test_Motors/Test_Motors.ino
    - python: "2.7"
      env:
        - PLATFORMIO_CI_EXTRA_ARGS="--board=due" PLATFORMIO_CI_SRC=DualVNH5019MotorShieldMod3/examples/Test_Motors/Test_Motors.ino
    - python: "2.7"
      env:
        - PLATFORMIO_CI_EXTRA_ARGS="--board=uno" PLATFORMIO_CI_SRC=DualVNH5019MotorShieldMod3/examples/Test_Motors/Test_Motors.ino
  allow_failures:
    - python: "2.7"
      env: PLATFORMIO_CI_EXTRA_ARGS="--board=uno" PLATFORMIO_CI_SRC=DualVNH5019MotorShieldMod3/examples/Demo/Demo.ino
    - python: "2.7"
      env: PLATFORMIO_CI_EXTRA_ARGS="--board=uno" PLATFORMIO_CI_SRC=DualVNH5019MotorShieldMod3/examples/Test_Motors/Test_Motors.ino

install:
  - pip install -U platformio

script:
  - platformio ci --lib="DualVNH5019MotorShieldMod3" $PLATFORMIO_CI_EXTRA_ARGS


 #- arduino --verify --board arduino:avr:uno $PWD/examples/Demo/Demo.ino
 #- arduino --verify --board arduino:avr:mega $PWD/examples/Demo/Demo.ino
 #- arduino --verify --board arduino:avr:uno $PWD/examples/Test_Motors/Test_Motors.ino
 #- arduino --verify --board arduino:avr:mega $PWD/examples/Demo/Demo.ino
